/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.13.0
 *
 * Project: 'Hello.Release+MPS3' 
 * Target:  'Release+MPS3' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE300MPS3.h"



#endif /* RTE_COMPONENTS_H */
